#!/bin/sh
#
#  Copyright 2014 Linagora, Université Joseph Fourier
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# The 'roboconf' user was created in the pre-install script
USER=roboconf-agent
GROUP=roboconf-agent

# Create the directory /etc/ directories
ROBOCONF_AGENT_ETC=/etc/roboconf-agent
mkdir -p $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true

mv /opt/roboconf-agent/etc/* $ROBOCONF_AGENT_ETC
rmdir /opt/roboconf-agent/etc
chown $USER:$GROUP $ROBOCONF_AGENT_ETC

# Ask for target-id using debconf (see debconf "templates" file),
# then replace target-id in roboconf-agent config (according to user input).
db_get roboconf-agent/target || true
sed -i "/target-id =/c target-id = $RET" $ROBOCONF_AGENT_ETC/net.roboconf.agent.configuration.cfg

# Create the directory /var/log/roboconf-agent
ROBOCONF_AGENT_VAR_LOG=/var/log/roboconf-agent
mkdir -p $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true

ROBOCONF_AGENT_VAR_LIB=/var/lib/roboconf-agent
mv /opt/roboconf-agent/data/* $ROBOCONF_AGENT_VAR_LIB
rmdir /opt/roboconf-agent/data
chown $USER:$GROUP $ROBOCONF_AGENT_VAR_LIB

# Register the agent's automatic startup
update-rc.d roboconf-agent defaults

# Start
set +e
if which invoke-rc.d >/dev/null 2>&1; then
   invoke-rc.d --force roboconf-agent start
else
   /etc/init.d/roboconf-agent start
fi

