#!/bin/sh
#
#  Copyright 2014 Linagora, Université Joseph Fourier
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################
#
# Post uninstallation script
#
################################################################################

set -e

ROBOCONF_AGENT_ETC=/etc/roboconf-agent
ROBOCONF_AGENT_VAR_LOG=/var/log/roboconf-agent
ROBOCONF_AGENT_VAR_LIB=/var/lib/roboconf-agent
ROBOCONF_AGENT_OPT=/opt/roboconf-agent

# Unregister the agent's automatic startup
update-rc.d roboconf-agent remove

if [ "$1" = "purge" ]; then
   # Remove all the work files of the agent
   rm -rf $ROBOCONF_AGENT_VAR_LIB || true
 
   # Remove all the agent config
   rm -rf $ROBOCONF_AGENT_ETC || true
fi
 
# Remove all the log files of the agent
rm -rf $ROBOCONF_AGENT_VAR_LOG || true

# Remove all the executables
rm -rf $ROBOCONF_AGENT_OPT || true   
