#!/bin/sh
#
# Copyright 2014-2016 Linagora, Université Joseph Fourier, Floralis
#
# The present code is developed in the scope of the joint LINAGORA -
# Université Joseph Fourier - Floralis research program and is designated
# as a "Result" pursuant to the terms and conditions of the LINAGORA
# - Université Joseph Fourier - Floralis research program. Each copyright
# holder of Results enumerated here above fully & independently holds complete
# ownership of the complete Intellectual Property rights applicable to the whole
# of said Results, and may freely exploit it in any manner which does not infringe
# the moral rights of the other copyright holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# The 'roboconf' user was created in the pre-install script
USER=roboconf-agent
GROUP=roboconf-agent

# Create the /ETC directory
ROBOCONF_AGENT_ETC=/etc/roboconf-agent
mv -n /opt/roboconf-agent/etc $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true
chown -R $USER:$GROUP $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true

# Update the logging configuration
sed -i -r 's/\$\{karaf\.data\}\/log/\/var\/log\/roboconf-agent/g' /etc/roboconf-agent/org.ops4j.pax.logging.cfg

# Ask for "parameters" using debconf (see debconf "templates" file),
# then replace "parameters" in roboconf-agent config (according to user input).
db_get roboconf-agent/target || true
if [ "$RET" != "other" ]; then
    sed -i "/parameters =/c parameters = $RET" $ROBOCONF_AGENT_ETC/net.roboconf.agent.configuration.cfg
fi

# Create the /VAR/LOG directory
ROBOCONF_AGENT_VAR_LOG=/var/log/roboconf-agent
mkdir -p $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true

# Move the data directory
ROBOCONF_AGENT_VAR_LIB=/var/lib/roboconf-agent
mv -n /opt/roboconf-agent/data $ROBOCONF_AGENT_VAR_LIB
chown -R $USER:$GROUP $ROBOCONF_AGENT_VAR_LIB

# Register the agent's automatic startup
update-rc.d roboconf-agent defaults

# Start
set +e
if which invoke-rc.d >/dev/null 2>&1; then
   invoke-rc.d --force roboconf-agent start
else
   /etc/init.d/roboconf-agent start
fi
