#!/bin/sh
#
#  Copyright 2014 Linagora, Université Joseph Fourier
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

# The 'roboconf' user was created in the pre-install script
USER=roboconf-dm
GROUP=roboconf-dm

# Create the directory /etc/ directories
ROBOCONF_DM_ETC=/etc/roboconf-dm
mkdir -p $ROBOCONF_DM_ETC > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_DM_ETC > /dev/null 2>&1 || true

mv /opt/roboconf-dm/etc/* $ROBOCONF_DM_ETC
rmdir /opt/roboconf-dm/etc
chown $USER:$GROUP $ROBOCONF_DM_ETC

# Create the directory /var/log/roboconf-dm
ROBOCONF_DM_VAR_LOG=/var/log/roboconf-dm
mkdir -p $ROBOCONF_DM_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_DM_VAR_LOG > /dev/null 2>&1 || true

ROBOCONF_DM_VAR_LIB=/var/lib/roboconf-dm
mv /opt/roboconf-dm/data/* $ROBOCONF_DM_VAR_LIB
rmdir /opt/roboconf-dm/data
chown $USER:$GROUP $ROBOCONF_DM_VAR_LIB

chmod 755 /opt/roboconf-dm/bin/karaf

# Register the dm's automatic startup
update-rc.d roboconf-dm defaults

# Start
if which invoke-rc.d >/dev/null 2>&1; then
   invoke-rc.d --force roboconf-dm start
else
   /etc/init.d/roboconf-dm start
fi
