#!/bin/sh
#
# Copyright 2014-2016 Linagora, Université Joseph Fourier, Floralis
#
# The present code is developed in the scope of the joint LINAGORA -
# Université Joseph Fourier - Floralis research program and is designated
# as a "Result" pursuant to the terms and conditions of the LINAGORA
# - Université Joseph Fourier - Floralis research program. Each copyright
# holder of Results enumerated here above fully & independently holds complete
# ownership of the complete Intellectual Property rights applicable to the whole
# of said Results, and may freely exploit it in any manner which does not infringe
# the moral rights of the other copyright holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

# The 'roboconf' user was created in the pre-install script
USER=roboconf-dm
GROUP=roboconf-dm

# Create the /ETC directory
ROBOCONF_DM_ETC=/etc/roboconf-dm
mv -n /opt/roboconf-dm/etc $ROBOCONF_DM_ETC > /dev/null 2>&1 || true
chown -R $USER:$GROUP $ROBOCONF_DM_ETC > /dev/null 2>&1 || true

# Update the logging configuration
sed -i -r 's/\$\{karaf\.data\}\/log/\/var\/log\/roboconf-dm/g' /etc/roboconf-dm/org.ops4j.pax.logging.cfg

# Create the /VAR/LOG directory
ROBOCONF_DM_VAR_LOG=/var/log/roboconf-dm
mkdir -p $ROBOCONF_DM_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_DM_VAR_LOG > /dev/null 2>&1 || true

# Move the data directory
ROBOCONF_DM_VAR_LIB=/var/lib/roboconf-dm
mv -n /opt/roboconf-dm/data $ROBOCONF_DM_VAR_LIB
chown -R $USER:$GROUP $ROBOCONF_DM_VAR_LIB

# Register the dm's automatic startup
update-rc.d roboconf-dm defaults

# Start
if which invoke-rc.d >/dev/null 2>&1; then
   invoke-rc.d --force roboconf-dm start
else
   /etc/init.d/roboconf-dm start
fi
