#!/bin/sh
#
#  Copyright 2014 Linagora, Université Joseph Fourier
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

set -e


# The 'roboconf' user was created in the pre-install script
USER=roboconf-agent
GROUP=roboconf-agent
RPM_SOURCE_DIR=/opt/roboconf-agent

tar -xzvf $RPM_SOURCE_DIR/roboconf-karaf-dist-agent-0.6-SNAPSHOT.tar.gz
cp -r roboconf-karaf-dist-agent-0.6-SNAPSHOT/* $RPM_SOURCE_DIR
rm -rf roboconf-karaf-dist-agent-0.6-SNAPSHOT
#rm $RPM_SOURCE_DIR/roboconf-karaf-dist-agent-0.6-SNAPSHOT.tar.gz

# Create the directory /etc/ directories
ROBOCONF_AGENT_ETC=/etc/roboconf-agent
mkdir -p $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true

cp -r /opt/roboconf-agent/etc/* $ROBOCONF_AGENT_ETC
chown $USER:$GROUP $ROBOCONF_AGENT_ETC

# Ask for target-id using debconf (see debconf "templates" file),
# then replace target-id in roboconf-agent config (according to user input).
#db_get roboconf-agent/target || true
#if [ "$RET" != "other" ]; then
#    sed -i "/target-id =/c target-id = $RET" $ROBOCONF_AGENT_ETC/net.roboconf.agent.configuration.cfg
#fi

# Create the directory /var/log/roboconf-agent
ROBOCONF_AGENT_VAR_LOG=/var/log/roboconf-agent
mkdir -p $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true

ROBOCONF_AGENT_VAR_LIB=/var/lib/roboconf-agent
mv /opt/roboconf-agent/data/* $ROBOCONF_AGENT_VAR_LIB
rmdir /opt/roboconf-agent/data
chown $USER:$GROUP $ROBOCONF_AGENT_VAR_LIB

# Start
set +e
/etc/init.d/roboconf-agent start


