#!/bin/sh
#
#  Copyright 2015-2016 Linagora, Université Joseph Fourier, Floralis
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

set -e

# The 'roboconf' user was created in the pre-install script
USER=roboconf-agent
GROUP=roboconf-agent
RPM_SOURCE_DIR=/opt/roboconf-agent

# Extract the TAR.GZ in the current directory.
# Do not export the root directory (the one which contains the Roboconf version).
tar -xzvf $RPM_SOURCE_DIR/roboconf-karaf-dist-agent-*.tar.gz -C $RPM_SOURCE_DIR --strip 1

# Delete the TAR.GZ
rm -rf $RPM_SOURCE_DIR/roboconf-karaf-dist-agent-*.tar.gz

# Create the /ETC directory
ROBOCONF_AGENT_ETC=/etc/roboconf-agent
mv -n /opt/roboconf-agent/etc $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true
chown -R $USER:$GROUP $ROBOCONF_AGENT_ETC > /dev/null 2>&1 || true

# Update the logging configuration
sed -i -r 's/\$\{karaf\.data\}\/log/\/var\/log\/roboconf-agent/g' /etc/roboconf-agent/org.ops4j.pax.logging.cfg

# Create the /VAR/LOG directory
ROBOCONF_AGENT_VAR_LOG=/var/log/roboconf-agent
mkdir -p $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_AGENT_VAR_LOG > /dev/null 2>&1 || true

# Move the data directory
ROBOCONF_AGENT_VAR_LIB=/var/lib/roboconf-agent
mv -n /opt/roboconf-agent/data $ROBOCONF_AGENT_VAR_LIB
chown -R $USER:$GROUP $ROBOCONF_AGENT_VAR_LIB

# Copy the man page
if [ -d "/usr/share/man/man1" ]; then
	cp -n /tmp/man/roboconf-agent.1.gz /usr/share/man/man1/
fi

# Start
set +e
/etc/init.d/roboconf-agent start
