#!/bin/sh
#
#  Copyright 2014 Linagora, Université Joseph Fourier
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################
#
# Post installation script
#
################################################################################

set -e


# The 'roboconf' user was created in the pre-install script
USER=roboconf-dm
GROUP=roboconf-dm
RPM_SOURCE_DIR=/opt/roboconf-dm

# FIXME: What??
tar -xzvf $RPM_SOURCE_DIR/roboconf-karaf-dist-dm-0.6-SNAPSHOT.tar.gz
cp -r roboconf-karaf-dist-dm-0.6-SNAPSHOT/* $RPM_SOURCE_DIR
rm -rf roboconf-karaf-dist-dm-0.6-SNAPSHOT

# Create the directory /etc/ directories
ROBOCONF_DM_ETC=/etc/roboconf-dm
mkdir -p $ROBOCONF_DM_ETC > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_dm_ETC > /dev/null 2>&1 || true

cp -r /opt/roboconf-dm/etc/* $ROBOCONF_DM_ETC
chown $USER:$GROUP $ROBOCONF_DM_ETC

# Create the directory /var/log/roboconf-dm
ROBOCONF_DM_VAR_LOG=/var/log/roboconf-dm
mkdir -p $ROBOCONF_DM_VAR_LOG > /dev/null 2>&1 || true
chown $USER:$GROUP $ROBOCONF_dm_VAR_LOG > /dev/null 2>&1 || true

ROBOCONF_DM_VAR_LIB=/var/lib/roboconf-dm
mv -n /opt/roboconf-dm/data/* $ROBOCONF_DM_VAR_LIB
rm -rf /opt/roboconf-dm/data
chown $USER:$GROUP $ROBOCONF_DM_VAR_LIB

# Start
set +e
/etc/init.d/roboconf-dm start
