#!/bin/sh
#
# Copyright 2015-2016 Linagora, Université Joseph Fourier, Floralis
#
# The present code is developed in the scope of the joint LINAGORA -
# Université Joseph Fourier - Floralis research program and is designated
# as a "Result" pursuant to the terms and conditions of the LINAGORA
# - Université Joseph Fourier - Floralis research program. Each copyright
# holder of Results enumerated here above fully & independently holds complete
# ownership of the complete Intellectual Property rights applicable to the whole
# of said Results, and may freely exploit it in any manner which does not infringe
# the moral rights of the other copyright holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
# Post uninstallation script
#
################################################################################

set -e

ROBOCONF_DM_ETC=/etc/roboconf-dm
ROBOCONF_DM_VAR_LOG=/var/log/roboconf-dm
ROBOCONF_DM_VAR_LIB=/var/lib/roboconf-dm
ROBOCONF_DM_OPT=/opt/roboconf-dm

# Unlike with Debian packages, there is no "purge" with RPM.
# So, we remove everything.
rm -rf $ROBOCONF_DM_VAR_LIB || true
rm -rf $ROBOCONF_DM_ETC || true
 
# Remove all the log files of the DM
rm -rf $ROBOCONF_DM_VAR_LOG || true

# Remove all the executables
rm -rf $ROBOCONF_DM_OPT || true   
